server:
    port: 8085

spring:
    application:
        name: bookstore-manager
    cloud:
        config:
            import-check:
                enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/bookstoredb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: appuser
        password: appPassword
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    security:
        user:
            name: admin
            password: admin123

logging:
    level:
        root: INFO
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'